### ISSUE TITLE
Database migration failed: manual action is required!

### ISSUE THREAD

**Issue by roscabgdn** [scandipwa/scandipwa-base#64]
I am following all the steps from the documentation but the install is breaking at step 5.
When I run the up -d command. 
In the logs I receive at Checking status of the magento database point the following: 
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Framework\Setup\Declaration\Schema\Db\SchemaBuilder::processReferenceKeys() must be of the type array, null given, called in /var/www/public/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php on line 127 and defined in /var/www/public/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php:137
app_1            | Stack trace:
app_1            | #0 /var/www/public/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php(127): Magento\Framework\Setup\Declaration\Schema\Db\SchemaBuilder->processReferenceKeys(NULL, Object(Magento\Framework\Setup\Declaration\Schema\Dto\Schema))
app_1            | #1 /var/www/public/vendor/magento/framework/Setup/Declaration/Schema/SchemaConfig.php(66): Magento\Framework\Setup\Declaration\Schema\Db\SchemaBuilder->build(Object(Magento\Framework\Setup\Declaration\Schema\Dto\Schema))
app_1            | #2 /var/www/public/vendor/magento/framework/Setup/Declaration/Schema/UpToDateDeclarativeSchema.php(56): Magento\Framework\Setup\Declaration\Schema\SchemaConfig->get in /var/www/public/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php on line 137
app_1            | 
app_1            | PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Framework\Setup\Declaration\Schema\Db\SchemaBuilder::processReferenceKeys() must be of the type array, null given, called in /var/www/public/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php on line 127 and defined in /var/www/public/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php:137
app_1            | Stack trace:
app_1            | #0 /var/www/public/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php(127): Magento\Framework\Setup\Declaration\Schema\Db\SchemaBuilder->processReferenceKeys(NULL, Object(Magento\Framework\Setup\Declaration\Schema\Dto\Schema))
app_1            | #1 /var/www/public/vendor/magento/framework/Setup/Declaration/Schema/SchemaConfig.php(66): Magento\Framework\Setup\Declaration\Schema\Db\SchemaBuilder->build(Object(Magento\Framework\Setup\Declaration\Schema\Dto\Schema))
app_1            | #2 /var/www/public/vendor/magento/framework/Setup/Declaration/Schema/UpToDateDeclarativeSchema.php(56): Magento\Framework\Setup\Declaration\Schema\SchemaConfig->get in /var/www/public/vendor/magento/framework/Setup/Declaration/Schema/Db/SchemaBuilder.php on line 137
app_1            | DB STATUS: 255 
app_1            | Database migration failed: manual action is required!
`

**To Reproduce**
Install scandipwa following the docs from github.

**Expected behavior**
Make the install work.

**Desktop (please complete the following information):**
-   OS: \[Ubuntu 18.04 LTS\]

**Comment by roscabgdn** [comment]
in the end it seems like it was a ceritificate problem. for some reason the certificate from
/usr/share/ca-certifiactes/extra was not ok.
